services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_class
    ports:
      - "5001:5000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
